# Default values for bingo.

replicaCount: 1

image:
  repository: ghcr.io/offendingcommit/bingo
  tag: latest
  pullPolicy: IfNotPresent

service:
  # Kubernetes service type (ClusterIP, NodePort, LoadBalancer)
  type: ClusterIP
  # Service port (the externally visible port)
  port: 80

# Container port (the port on which your app listens)
containerPort: 8080

# Environment variables for the container
env:
  PORT: "8080"
  METRICS_PORT: "9090"

# ConfigMap data for phrases.
# Edit or extend below key/value pairs as needed.
phrases:
  -  Can't nice things
  -  Techno babble
  -  Hell yeah!
  -  Raided
  -  That's Noice
  -  Position one
  -  How's my audio
  -  Someone redeems hydrate
  -  Threaten good time
  -  Mentions mods
  -  Says texas
  -  Spins bonus wheel
  -  Join discord
  -  Holy smokes!
  -  Says Cats or Dogs
  -  Doot doots
  -  Makes air quotes
  -  Talks about ellee
  -  Zoom
  -  Sight lines
  -  Talks about palia
  -  Says Commitee
  -  Dance party
  -  That's nuts!
  -  Says vel
  -  Says LGS
  -  Says Harlequin Law
  -  Says BBQ
  -  Says Pizza
  -  Says Sushi
  -  Says DevOps
  -  Says Kubernetes
  -  Says Palia Partner
  -  Offending Tide
  -  Thanks for the bitties
  -  See Grand baby

# Overrides for the fully qualified resource names.
nameOverride: ""
fullnameOverride: "" 