apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bingo.fullname" . }}
  labels:
    app: {{ include "bingo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "bingo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bingo.name" . }}
    spec:
      containers:
        - name: {{ include "bingo.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: METRICS_PORT
              value: {{ .Values.env.METRICS_PORT | quote }}
          volumeMounts:
            - name: config
              mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            name: {{ include "bingo.fullname" . }}-config 