# All application constants

# Text constants
HEADER_TEXT = "COMMIT !BINGO"
HEADER_TEXT_COLOR = "#0CB2B3"
FREE_SPACE_TEXT = "FREE MEAT"
FREE_SPACE_TEXT_COLOR = "#FF7f33"

# Colors
TILE_CLICKED_BG_COLOR = "#100079"
TILE_CLICKED_TEXT_COLOR = "#1BEFF5"
TILE_UNCLICKED_BG_COLOR = "#1BEFF5"
TILE_UNCLICKED_TEXT_COLOR = "#100079"
HOME_BG_COLOR = "#100079"
STREAM_BG_COLOR = "#00FF00"

# Fonts
HEADER_FONT_FAMILY = "'Super Carnival', sans-serif"
BOARD_TILE_FONT = "Inter"
BOARD_TILE_FONT_WEIGHT = "700"
BOARD_TILE_FONT_STYLE = "normal"

# Board configuration
BOARD_SIZE = 5  # 5x5 grid
FREE_SPACE_POSITION = (2, 2)  # Middle of the board